name: Build and deploy Spfx

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout files
        uses: actions/checkout

      - name: Setup Node.js environment
        uses: actions/setup-node
        with:
          node-version: '18.18'
          cache: 'npm'

      - name: npm install
        run: npm install

      - name : gulp build
        run: gulp build --ship

      - name : gulp bundle
        run: gulp bundle --ship

      - name : gulp package
        run: gulp package-solution --ship
    
      - name: github context output
        run: echo "${{ toJson(github)}}"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact
        with:
          name: my-artifact
          path: sharepoint/solution/
          
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact
        with:
          name: my-artifact
  
      - name: Setup Node.js environment
        uses: actions/setup-node
        with:
          node-version: '18.18'

      - name: npm install custom
        run: npm i -g @pnp/cli-microsoft365

      - name: M365 login
        id: login
        uses: pnp/action-cli-login
        with:
          ADMIN_USERNAME:  ${{ secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD:  ${{ secrets.ADMIN_PASSWORD }}
          
      - name: Deploy app to tenant app catalog
        id: M365clideploy
        uses: pnp/action-cli-deploy
        with:
          APP_FILE_PATH: my-first-webpart.sppkg
          SKIP_FEATURE_DEPLOYMENT: true
          OVERWRITE: true

      - name: Get the id of the app deployed
        run: echo "The id of the app deployed is ${{ steps.M365clideploy.outputs.APP_ID }}"

      # - name: Deploy app to a site collection app catalog
      #   id: M365clideployapp
      #   uses: pnp/action-cli-deploy@v3.0.1
      #   with:
      #     APP_FILE_PATH: my-first-webpart.sppkg
      #     SCOPE: sitecollection
      #     SITE_COLLECTION_URL: https://tgshl.sharepoint.com/sites/Dev

      # - name: Add spfx package in catalog
      #   run: m365 spo app add -p my-first-webpart.sppkg --overwrite

      # - name: Deploy the Spfx package
      #   run: m365 spo app deploy --name my-first-webpart.sppkg

      # - name: install spfx package in dev site
      #   run: m365 spo app install --id "b4194485-6773-42bd-8bd6-fbfc5bc21e9b" --siteUrl "https://tgshl.sharepoint.com/sites/Dev"

      
