name: Build and deploy Spfx

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: hello world
        run: echo hello

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.0
        with:
          node-version: '18.18'
          
      - name: npm install
        run: npm install
    
      - name: github context output
        run: echo "${{ toJson(github)}}"
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: hello 2
        run: |
          echo hellow 
          echo hellowww