name: m365 test
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.0
        with:
          node-version: '18.18'
      - name: npm install custom
        run: npm i -g @pnp/cli-microsoft365
      - name: Connect to app Catalog site
        run: m365 login  -t password -u "Azureuser@tgshl.onmicrosoft.com" -p ":Z6A:SJy89ET:vy"
